spring.application.name: service

spring:
  profiles: default
  datasource: 
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    initialize: true
    continue-on-error: false
    schema:
    - classpath:data/to-do-task-schema.sql
    data:
    - classpath:data/to-do-task-data.sql